config/routes.rb
Rails.application.routes.draw do
  resources :musica_selecionadas
  resources :eventos
  root 'now#index', as: 'now_index'

  get 'now/index'

  resources :musicas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evento.rb
class Evento < ApplicationRecord
  has_many :musica_selecionadas, dependent: :destroy

  def to_s
    nome || '<evento sem nome>'
  end
end

app/models/musica.rb
class Musica < ApplicationRecord
  has_many :musica_selecionadas

  before_destroy :ensure_not_referenced_by_musica_selecionada

  validates :titulo, :temas, :cifras, presence: true
  validates :titulo, uniqueness: true
  validates :titulo, length: {minimum: 3}
  validates :popularidade, numericality: { greater_than_or_equal_to: 0.0 }, allow_blank: true
  validates :url_cifras, allow_blank: true, format: {
  	with: /\Ahttps?:\/\//
  }

  def to_s
    titulo || '<música sem título>'
  end

  private

  def ensure_not_referenced_by_musica_selecionada
    unless musica_selecionadas.empty?
      errors.add :base, 'Foi selecionada para algum evento'
      throw :abort
    end
  end
end

app/models/musica_selecionada.rb
class MusicaSelecionada < ApplicationRecord
  belongs_to :musica
  belongs_to :evento
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/current_event.rb
module CurrentEvent

  private

  def obter_evento_selecionado
    @evento = Evento.find(session[:evento_id])
  rescue ActiveRecord::RecordNotFound
    @evento = Evento.create
    session[:evento_id] = @evento.id
    @evento
  end

  def selecionar_evento
    session[:evento_id] = @evento.id
  end

end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  include CurrentEvent

  before_action :obter_evento_selecionado, only: [:index]
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_evento
    @evento = Evento.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def evento_params
    params.require(:evento).permit(:nome, :data, :topicos, :celebrante)
  end
end

app/controllers/musica_selecionadas_controller.rb
class MusicaSelecionadasController < ApplicationController
  include CurrentEvent

  before_action :obter_evento_selecionado, only: [:create]
  before_action :set_musica_selecionada, only: [:show, :edit, :update, :destroy]

  # GET /musica_selecionadas
  # GET /musica_selecionadas.json
  def index
    @musica_selecionadas = MusicaSelecionada.all
  end

  # GET /musica_selecionadas/1
  # GET /musica_selecionadas/1.json
  def show
  end

  # GET /musica_selecionadas/new
  def new
    @musica_selecionada = MusicaSelecionada.new
  end

  # GET /musica_selecionadas/1/edit
  def edit
  end

  # POST /musica_selecionadas
  # POST /musica_selecionadas.json
  def create
    musica = Musica.find(params[:musica_id])
    @musica_selecionada = @evento.musica_selecionadas.build(
      musica: musica,
      momento: params[:momento] || '<momento não nomeado>'
    )

    respond_to do |format|
      if @musica_selecionada.save
        format.html { redirect_to @musica_selecionada.evento, notice: 'Musica selecionada was successfully created.' }
        format.json { render :show, status: :created, location: @musica_selecionada }
      else
        format.html { render :new }
        format.json { render json: @musica_selecionada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musica_selecionadas/1
  # PATCH/PUT /musica_selecionadas/1.json
  def update
    respond_to do |format|
      if @musica_selecionada.update(musica_selecionada_params)
        format.html { redirect_to @musica_selecionada, notice: 'Musica selecionada was successfully updated.' }
        format.json { render :show, status: :ok, location: @musica_selecionada }
      else
        format.html { render :edit }
        format.json { render json: @musica_selecionada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musica_selecionadas/1
  # DELETE /musica_selecionadas/1.json
  def destroy
    @musica_selecionada.destroy
    respond_to do |format|
      format.html { redirect_to musica_selecionadas_url, notice: 'Musica selecionada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musica_selecionada
      @musica_selecionada = MusicaSelecionada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musica_selecionada_params
      params.require(:musica_selecionada).permit(:momento, :musica_id, :evento_id)
    end
end

app/controllers/musicas_controller.rb
class MusicasController < ApplicationController
  before_action :set_musica, only: [:show, :edit, :update, :destroy]

  # GET /musicas
  # GET /musicas.json
  def index
    @musicas = Musica.all
  end

  # GET /musicas/1
  # GET /musicas/1.json
  def show
  end

  # GET /musicas/new
  def new
    @musica = Musica.new
  end

  # GET /musicas/1/edit
  def edit
  end

  # POST /musicas
  # POST /musicas.json
  def create
    @musica = Musica.new(musica_params)

    respond_to do |format|
      if @musica.save
        format.html {redirect_to @musica, notice: 'Musica was successfully created.'}
        format.json {render :show, status: :created, location: @musica}
      else
        puts @musica.errors.full_messages
        format.html {render :new}
        format.json {render json: @musica.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /musicas/1
  # PATCH/PUT /musicas/1.json
  def update
    respond_to do |format|
      if @musica.update(musica_params)
        format.html {redirect_to @musica, notice: 'Musica was successfully updated.'}
        format.json {render :show, status: :ok, location: @musica}
      else
        format.html {render :edit}
        format.json {render json: @musica.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /musicas/1
  # DELETE /musicas/1.json
  def destroy
    @musica.destroy
    respond_to do |format|
      format.html {redirect_to musicas_url, notice: 'Musica was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_musica
    @musica = Musica.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def musica_params
    params.require(:musica).permit(:titulo, :musico, :temas, :url_cifras, :cifras, :popularidade)
  end
end

app/controllers/now_controller.rb
class NowController < ApplicationController
  include CurrentEvent

  def index
    @evento = obter_evento_selecionado if @evento.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/musica_selecionadas_helper.rb
module MusicaSelecionadasHelper
end

app/helpers/musicas_helper.rb
module MusicasHelper
end

app/helpers/now_helper.rb
module NowHelper
end

app/views/eventos/_form.html.erb
<%= form_with(model: evento, local: true) do |form| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :evento_nome %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.datetime_select :data, id: :evento_data %>
  </div>

  <div class="field">
    <%= form.label :topicos %>
    <%= form.text_field :topicos, id: :evento_topicos %>
  </div>

  <div class="field">
    <%= form.label :celebrante %>
    <%= form.text_field :celebrante, id: :evento_celebrante %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data</th>
      <th>Topicos</th>
      <th>Celebrante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.nome %></td>
        <td><%= evento.data %></td>
        <td><%= evento.topicos %></td>
        <td><%= evento.celebrante %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @evento.nome %>
</p>

<p>
  <strong>Data:</strong>
  <%= @evento.data %>
</p>

<p>
  <strong>Topicos:</strong>
  <%= @evento.topicos %>
</p>

<p>
  <strong>Celebrante:</strong>
  <%= @evento.celebrante %>
</p>


<p>
  <strong>Musicas:</strong>
  <ul>
    <% @evento.musica_selecionadas.each do |selecao| %>
      <li>
        <%= "#{selecao.momento}: #{selecao.musica.titulo}" %>
        <%= link_to 'Edit', edit_musica_selecionada_path(selecao) %>
        <%= link_to 'Show', selecao.musica %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lista de Músicas</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header class="main">
  <%= image_tag 'logo.svg', alt: 'Lista de Músicas' %>
  <h1>Pray list<%= @page_title %></h1>
</header>
<section class='content'>
  <nav class="side_nav">
    <ul>
      <li><a href="/">Agora</a></li>
      <li><a href="/eventos">Eventos</a></li>
      <li><a href="/musicas">Musicas</a></li>
      <li><a href="/chat">Chat</a></li>
    </ul>
  </nav>

  <main class="<%= controller.controller_name %>">
    <%= yield %>
  </main>
</section>

</body>
</html>

app/views/musica_selecionadas/_form.html.erb
<%= form_with(model: musica_selecionada, local: true) do |form| %>
  <% if musica_selecionada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(musica_selecionada.errors.count, "error") %> prohibited this musica_selecionada from being saved:</h2>

      <ul>
      <% musica_selecionada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :momento %>
    <%= form.text_field :momento, id: :musica_selecionada_momento %>
  </div>

  <div class="field">
    <%= form.label :musica_id %>
    <%= form.collection_select :musica_id, Musica.all.sort, :id, :titulo, prompt: "Selecione uma música" %>
  </div>

  <div class="field">
    <%= form.label :evento_id %>
    <%= form.collection_select :evento_id, Evento.all.sort, :id, :nome, prompt: "Selecione um evento" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/musica_selecionadas/edit.html.erb
<h1>Editing Musica Selecionada</h1>

<%= render 'form', musica_selecionada: @musica_selecionada %>

<%= link_to 'Show', @musica_selecionada %> |
<%= link_to 'Back', musica_selecionadas_path %>

app/views/musica_selecionadas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Musica Selecionadas</h1>

<table>
  <thead>
    <tr>
      <th>Momento</th>
      <th>Musica</th>
      <th>Evento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musica_selecionadas.each do |musica_selecionada| %>
      <tr>
        <td><%= musica_selecionada.momento %></td>
        <td><%= musica_selecionada.musica %></td>
        <td><%= musica_selecionada.evento %></td>
        <td><%= link_to 'Show', musica_selecionada %></td>
        <td><%= link_to 'Edit', edit_musica_selecionada_path(musica_selecionada) %></td>
        <td><%= link_to 'Destroy', musica_selecionada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Musica Selecionada', new_musica_selecionada_path %>

app/views/musica_selecionadas/new.html.erb
<h1>New Musica Selecionada</h1>

<%= render 'form', musica_selecionada: @musica_selecionada %>

<%= link_to 'Back', musica_selecionadas_path %>

app/views/musica_selecionadas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Momento:</strong>
  <%= @musica_selecionada.momento %>
</p>

<p>
  <strong>Musica:</strong>
  <%= @musica_selecionada.musica %>
</p>

<p>
  <strong>Evento:</strong>
  <%= @musica_selecionada.evento %>
</p>

<%= link_to 'Edit', edit_musica_selecionada_path(@musica_selecionada) %> |
<%= link_to 'Back', musica_selecionadas_path %>

app/views/musicas/_form.html.erb
<%= form_with(model: musica, local: true) do |form| %>
  <% if musica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(musica.errors.count, "error") %> prohibited this musica from being saved:</h2>

      <ul>
      <% musica.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :musica_titulo %>
  </div>

  <div class="field">
    <%= form.label :musico %>
    <%= form.text_field :musico, id: :musica_musico %>
  </div>

  <div class="field">
    <%= form.label :temas %>
    <%= form.text_field :temas, id: :musica_temas %>
  </div>

  <div class="field">
    <%= form.label :url_cifras %>
    <%= form.text_field :url_cifras, id: :musica_url_cifras %>
  </div>

  <div class="field">
    <%= form.label :cifras %>
    <%= form.text_area :cifras, id: :musica_cifras, rows: 20, cols: 60 %>
  </div>

  <div class="field">
    <%= form.label :popularidade %>
    <%= form.number_field :popularidade, id: :musica_popularidade %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar' %>
    <%= link_to 'Cancelar', musicas_path %>
  </div>
<% end %>

app/views/musicas/edit.html.erb
<h1>Editing Musica</h1>

<%= render 'form', musica: @musica %>

app/views/musicas/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Músicas</h1>

<table>
  <tfoot>
  <tr>
    <td colspan="2">
      <%= link_to 'Nova Música', new_musica_path %>
    </td>
  </tr>
  </tfoot>
  <tbody>
  <% cache @musicas do %>
    <% @musicas.each do |musica| %>
      <% cache musica do %>
        <tr class="musica <%= cycle('list_line_odd', 'list_line_even') %>">

          <td>
            <h2 class="titulo"><%= musica.titulo %></h2>
            <h3 class='musico'><%= musica.musico %></h3>
            <div class='temas'><%= musica.temas %></div>
            <%= button_to 'Selecionar', musica_selecionadas_path(musica_id: musica) %>
          </td>

          <td class="actions">
            <ul>
              <li><%= link_to 'Show', musica %></li>
              <li><%= link_to 'Edit', edit_musica_path(musica) %></li>
              <li>
                <%= link_to 'Destroy',
                            musica,
                            method: :delete,
                            data: {confirm: 'Tem certeza?'} %>
              </li>
            </ul>
          </td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/musicas/new.html.erb
<h1>New Musica</h1>

<%= render 'form', musica: @musica %>

app/views/musicas/show.html.erb
<p id="notice"><%= notice %></p>
<div class="musica">
    <h1 class="titulo"><%= @musica.titulo %></h1>

  <p>
    <span class='musico'><%= @musica.musico %></span>
  </p>

  <p>
    <span class="temas"><%= @musica.temas %></span>
  </p>

  <p>
    <strong>Popularidade:</strong>
    <span class="popularidade"><%= @musica.popularidade %></span>
  </p>

  <p>
    <strong>Cifras externas:</strong>
    <span class="url_cifras"><a href="<%= @musica.url_cifras %>"><%= @musica.url_cifras %></a></span>
  </p>

  <p>
    <strong>Nosso arranjo:</strong>
    <pre class="cifras"><%= @musica.cifras %></pre>
  </p>

</div>
<%= link_to 'Edit', edit_musica_path(@musica) %> |
<%= link_to 'Back', musicas_path %>

app/views/now/index.html.erb
<% if notice %>
  <aside id='notice'><%= notice %></aside>
<% end %>

<h1>Músicas para <%= @evento %></h1>

<ul class='musicas'>

    <% @evento.musica_selecionadas.each do |selecao| %>
      <li>
        <%= "#{selecao.momento}: #{selecao.musica.titulo}" %>
        <%= link_to 'Edit', edit_musica_selecionada_path(selecao) %>
        <%= link_to 'Show', selecao.musica %>
      </li>
    <% end %>
  </ul>